name: inventory-system

services:
  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    platform: linux/amd64
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
    volumes:
      - api_data:/app/api/data
    networks:
      - app-network

  ui:
    build:
      context: ..
      dockerfile: docker/ui.Dockerfile
      args:
        - VITE_API_URL=/api
    platform: linux/amd64
    ports:
      - '8080:8080'
    depends_on:
      - api
    networks:
      - app-network

volumes:
  api_data:

networks:
  app-network:
    driver: bridge
